import { Poppins} from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata = {
  title: "Codi",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="es" 
      className={`${poppins.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}
        <Toaster position="bottom-right" richColors />
      </body>
    </html>
  );
}
